config/routes.rb
Rails.application.routes.draw do
  
  localized do       
    get "/"                => "pages#home", :as => :locale_root
    get "contact"          => "pages#contact"
	  get "marfa"            => "pages#marfa"
    get "overview"         => "pages#overview"
    get "store"            => "pages#store"
    get "testpage"         => "pages#testpage"
    get "terms"            => "pages#terms"
    get "thanks"           => "pages#thanks"
    post "thanks"          => "pages#thanks"
    
    match "/400"           => "errors#bad_request", :via => :all
    match "/404"           => "errors#not_found", :via => :all
    match "/422"           => "errors#unprocessable_entity", :via => :all
    match "/500"           => "errors#internal_server_error", :via => :all
  end
  
  root                        "pages#home"
  
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<% if params[:action] == "home" %>
	  <span class="home-page"><%= "©#{Time.now.strftime("%Y")} The Lighthouse Unlimited, Inc. #{t :copyright_all_rights} - #{t :lightbe_credit} " %><span class="font-weight-bold"><%= link_to "LightBe Corp", "https://www.lightbe.com/", target: "_blank" %></span></span>
	<% else %>
		<%= link_to "#{t :link_terms}", terms_path %><br>
	  <%= "©#{Time.now.strftime("%Y")} The Lighthouse Unlimited, Inc. #{t :copyright_all_rights} - #{t :lightbe_credit} " %><span class="font-weight-bold"><%= link_to "LightBe Corp", "https://www.lightbe.com/", target: "_blank" %></span>
	<% end %>
</div>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-md navbar-custom">
  <div class="container-fluid">
    <!-- <div class="navbar-header">
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-main-collapse"> <i class="fas fa-bars"></i> </button>
			<%= link_to " #{t :store_name}", locale_root_path, class: "navbar-brand" %>
		</div> -->

 	 <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-main-collapse"> <i class="fas fa-bars"></i> </button>
	 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-main-collapse">
			
			<%= link_to " #{t :store_name}", locale_root_path, class: "navbar-brand" %>

      <ul class="navbar-nav">
				<li class="nav-item nav-link text-fb-link"><%= link_to "https://www.facebook.com/lighthouseunlimited/", target: "_blank" do %><i class="fab fa-facebook-f"></i><% end %></li>
				<% if Rails.env.development? %>
	        <li class="nav-item nav-link"><%= link_to "#{t :english}", locale: "en" %></li>
	        <li class="nav-item nav-link"><%= link_to "#{t :spanish}", locale: "es" %></li>
				<% end %>
      </ul>
 
			<ul class="navbar-nav ml-auto">
      <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
      	<li class="hidden"> <a href="#page-top"></a> </li>
        <li class="nav-item nav-link"><%= link_to "#{t :link_overview}", overview_path %></li>
				<% if Rails.env.development? %><li class="nav-item nav-link"><%= link_to "#{t :link_store}", store_path %></li><% end %>
        <li class="nav-item nav-link"><%= link_to "#{t :link_contact}", contact_path %></li>
        <li class="nav-item nav-link"><%= link_to "#{t :link_marfa}", marfa_path %></li>
        <% if Rails.env.development? %><li class="nav-item nav-link"><%= link_to "#{t :link_testpage}", testpage_path %></li><% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse --> 
  </div>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <!-- /.container --> 
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"> type="text/javascript"</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
		<!-- Global Site Tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-107917100-1"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-107917100-1');
		</script>
    <meta charset="utf-8">
		<meta name="google-site-verification" content="gSDl10OgjQK-uTSbRWpu2NS-qoTpu6hLtvLrjRWWNf0" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
		<meta name="wot-verification" content="9145e5342dd6b1976fec"/>
		<%= display_meta_tags site: "#{t :meta_site}", title: "#{t :meta_title}", description: "#{t :meta_desc}", keywords: "#{t :meta_keywords}", og: { type: "website", site_name: :site, title: :full_title, description: :description, url: "https://www.lighthousemarfa.com/", image: "https://nbcbigbend.s3.us-west-2.amazonaws.com/headerlighthouselandscape.jpg", locale: "en", "locale:alternate": "es" }, fb: { pages: "601169346939392" } %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  	<%= favicon_link_tag "/favicon.ico" %>
    <%= render 'layouts/shim' %> 
  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <div class="container-fluid"> 
		<!-- Don't display the navbar for home, display flash message at the top of the page -->
			<% if params[:action] == "home" %>
	      <% flash.each do |key, value| %>
	        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	      <% end %>
			<% else %>
		<!-- Display flash message below the navbar -->
				<%= render "layouts/navbar" %>
			<% end %>
      <%= yield %>
		<!-- Don't display the footer for home -->
			<% if params[:action] == "home" %> 
			<% else %>
				<%= render "layouts/footer" %>
			<% end %>
    </div>
    <%= javascript_include_tag "application" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>